---
title: "R Notebook"
output: html_notebook
---

```{r}
# Load necessary libraries
library(rvest)
library(pdftools)
library(dplyr)
library(tidyverse)
library(janitor)
```


```{r}
file_path <- "special_permits_phmsa.html"
page <- read_html(file_path)
```

```{r}
permit_links <- page |>
  html_nodes('a[href*="hazmat/documents/offer/"]') |>
  html_attr('href')
```

```{r}
permit_numbers <- page |>
  html_nodes('a[href*="hazmat/documents/offer/"]') |>
  html_text(trim = TRUE)
```

```{r}
full_permit_links <- paste0("https://www.phmsa.dot.gov/", permit_links)
```

```{r}
# Create a data frame with permit numbers and their PDF links
all_permits <- data.frame(
  permit_num = permit_numbers,
  pdf_link = full_permit_links
)
```

```{r}
all_permits |>
  get_dupes()
```

```{r}
cleaned_permits <- all_permits |>
  distinct()
```

```{r}
search_string <- "RAIL FREIGHT"

search_in_pdf <- function(link, search_string) {
    text <- pdf_text(link)
    any(grepl(search_string, text, ignore.case = TRUE))
}

cleaned_permits <- cleaned_permits |>
    mutate(found = sapply(pdf_link, search_in_pdf, search_string = search_string))
```

